# -*- coding: utf-8 -*-
"""Assignment8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p7fPb9sZuxQJYqcTjO5rs-GmJ3UdGSEO
"""

#name ANUJ TADKASE
#DIV CS AI
#ROLL NUM 64
#BATCH 2


#use inbuilt titantic
#plot box plot for distribution of age with respect to each gender alongwith the information about whether they survived or not
#column names,gender and age
#assignment9
#write observations on the inference from the above statistics

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('titanic.csv')
data

plt.figure(figsize=(10, 6))
sns.boxplot(x='Sex', y='Age', hue='Survived', data=data)
plt.title('Age Distribution by Gender and Survival Status')
plt.xlabel('Gender')
plt.ylabel('Age')
plt.legend(title='Survived', labels=['Orange'])
plt.legend(title='NOT Survived', labels=['Blue'])
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns



plt.figure(figsize=(12, 8))


sns.catplot(x='Sex', y='Age', hue='Survived', col='Pclass', data=data, kind='box', height=6, aspect=1.2)


plt.suptitle('Age Distribution by Gender, Pclass, and Survival Status', y=1.02)
plt.xlabel('Gender')
plt.ylabel('Age')


plt.show()

# Create a catplot using Seaborn
plt.figure(figsize=(10, 6))
sns.set(style="whitegrid")  # Set the style of the plot

# Create a catplot using Seaborn
sns.catplot(x='Sex', y='Age', hue='Survived', data=data, kind='box', palette='Set2')
plt.title('Age Distribution by Gender and Survival Status')
plt.xlabel('Gender')
plt.ylabel('Age')


plt.show()

#ANALYSIS
#blue=not survived passsengers
#median age of male passengers who did not survive is about 28
#median age of femaile passengers who did not survive is about 25

plt.figure(figsize=(10, 6))
sns.boxplot(x='Survived', y='Age', data=data, palette='Set3')
plt.xlabel('Survived')
plt.ylabel('Age')
plt.title('Age vs. Survival')
plt.xticks(ticks=[0, 1], labels=['Did Not Survive', 'Survived'])
plt.show()
#

survival_rates = data.groupby('Sex')['Survived'].mean()

# Create a bar chart
plt.figure(figsize=(8, 6))
plt.bar(survival_rates.index, survival_rates.values, color=['green', 'red'])
plt.title('Survival Rate by Gender')
plt.xlabel('Gender')
plt.ylabel('Survival Rate')
plt.show()
#survival rate by gender
#we can see that female have more survival rate as compared to male

plt.figure(figsize=(10, 6))
sns.boxplot(x='Age', y='Fare', data=data, palette='Set3')
plt.xlabel('age')
plt.ylabel('fare')
plt.title('Age vs. fare')

plt.show()

sns.catplot(x='Pclass',y='Survived',data=data,kind='box')

import pandas as pd
import matplotlib.pyplot as plt


# Calculate survival rates by passenger class
survival_rates = data.groupby('Pclass')['Survived'].mean()

# Create a bar chart
plt.figure(figsize=(8, 6))
plt.bar(survival_rates.index, survival_rates.values, color=['blue', 'lightgreen', 'red'])
plt.title('Survival Rate by Passenger Class')
plt.xlabel('Passenger Class')
plt.ylabel('Survival Rate')
plt.xticks(ticks=[1, 2, 3], labels=['1st Class[High]', '2nd Class[Middle]', 'Class 3[Low]'])
plt.show()
#we can analyse that class 3 people have the least survival rate

