# -*- coding: utf-8 -*-
"""Lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eUPXoUf8BTOL1LJc67I9Uug7WupmpHY4
"""

#roll num 64 Name:Anuj Tadkase
#cs ai A


import pandas as pd

import matplotlib.pyplot as plt

#3. Descriptive Statistics –
     #   Measures of Central Tendency and variability perform the following operations on
       # any open-source dataset (e.g., data.csv) for a dataset (age, income etc.) with
       # numeric variables grouped by one of the qualitative (categorical) variable.
       # For example, if your categorical variable is age groups and quantitative variable is
       # income, then provide summary statistics of income grouped by the age groups.
      # Create a list that contains a numeric value for each response to the categorical
       #variable.

mydata = pd.read_csv("Customers.csv")
print(mydata)

mydata.mean()
#mean of data

mydata.mode()
#modal tendency of data

mydata.median()
#median of data

mydata.groupby("Age").mean()
#grouping by age

mydata.groupby(["Profession"]).mean()
#grouping by profession

mydata.groupby(["Annual Income ($)"]).mean()
#grouping by profession

mydata.groupby(["Work Experience"]).mean()
#grouping by work experience

mydata.std()
#gives std deviation

mydata.info()
#gives information about columns

mydata.shape
#gives rows and columns

mydata.describe()
#describes information about dataset

mydata.std()
#for std deviation

mydata.var()
#for finding out variance

boxplot = mydata.boxplot(column=["Age" ])

mydata.plot(kind = 'box',  y = 'Annual Income ($)')
plt.show()

mydata.plot(kind = 'box',x='Age',  y = 'Annual Income ($)')
#boxplot



mydata.plot(kind = 'hist',y = 'Annual Income ($)')
plt.show()
#histogram graph

mydata.plot(kind = 'scatter', x = 'Age', y = 'Annual Income ($)')
plt.show()
#line graph

df2 = mydata.sort_values(by='Profession')
print(df2)
#sorting by artist first



df2 = mydata.sort_values(by='Age')
print(df2)
#sorting by 0 - 99 age ascending order



mydata.groupby("Profession").mean()
#grouped data starting from profession

x = map(mydata, ('Profession', 'Age'))
print(x)

df3 = mydata.sort_values(by='Gender')
print(df3)
#sorted by gender fm first

#n summary, the analysis conducted on the open-source dataset (data.csv) involved calculating Measures of Central Tendency and Variability for numeric variables categorized by a qualitative variable.
# By grouping data based on this categorical variable (e.g., age groups) and analyzing a quantitative variable (e.g., income),
# we generated a list of numerical values that represented summary statistics for each category.
# This approach enabled a comprehensive understanding of how central tendencies and variability vary across different groups, offering valuable insights
# into the dataset's distribution and trends.We also found out about various mean incomes,shape of graphs,
#highest income is of executive
#lowest is of homemaker
#we have also used various graphs like historgram and scatter graphs for plotting various variables and represent data  also made use of box plot to find out median and various ranges