# -*- coding: utf-8 -*-
"""lab5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T4evvPcfyVbmW-NDowMLP6PIpFT8gtXc
"""

#Implement logistic regression using Python/R to perform classification on   Social_Network_Ads.csv dataset.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression



dataset = pd.read_csv('Salary_Data.csv')
print(dataset)

X = dataset.iloc[:, :-1].values
#index location
y = dataset.iloc[:, -1].values
print (X)

print (y)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/5, random_state = 0 )


regressor = LinearRegression()

regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print(y_pred)

print(regressor.predict([[12]]))
#PREDICT THE SALARY OF EMPLOYEE WITH 12 YEARS EXPERIENCE

#PRINT FINAL VALUES OF COEFFICIENTS B0 B1
print(regressor.intercept_)
print(regressor.coef_)
#equation
#Salary=26780+9312(Year of experience)
#y=b0+b1(x)