# -*- coding: utf-8 -*-
"""TUTORIAL5DV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QxWmlANhz8cuwLmggeapeoAoc7c4Yj3_
"""

#name ANUJ TADKASE
#BATCH 2
#ROLL NUM 64
#PRN 12211778
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

dataset = {
'treeheight' : [35, 49, 27, 33, 60, 21, 45, 51],
'treediameter' : [8, 9, 7, 6, 13, 7, 11, 12]
}
df = pd.DataFrame(dataset)
df

x = pd.DataFrame(df.corr())
x
r = np.asarray(x.iloc[[1], [0]])
r

x = 1 - (r**2)
y = x/6
z = (math.sqrt(y))
t = r/z
print(t)

dataset2={
    'rainfall':[12.3,13.7,14.5,11.2,13.2,14.1,12.0],
    'yield':[6.25,8.02,8.42,5.27,7.21,8.71,5.68]
}
df=pd.DataFrame(dataset2)
df

x=pd.DataFrame(df.corr())
x

r=np.array(x.iloc[[1],[0]])
r

x=1-(r**2)
y=x/6
z=(math.sqrt(y))
t=r/z
print(t)