# -*- coding: utf-8 -*-
"""tutorial6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_FFtgUywfBxDSbKwO0-mIhJA-yc9pDe0
"""

import pandas as pd
#Name:ANUJ TADKASE
#DIV :CS AI A
#PRN:12211778
#BATCH 2

import numpy as np
import matplotlib.pyplot as plt

x=np.array([1400,1600,1700,1875,1100,1550,2350,2450,1425,1700])
y=np.array([245,312,279,308,199,219,405,324,319,255])
y_avg=np.mean(y)
#linear regression
coefficients=np.polyfit(x,y,1)#linear regression degree 1
slope=coefficients[0]
intercept = coefficients[1]
y_pred= slope*x + intercept

print("Average:",y_avg)
print("actual:",y)
print("Predicted:",y_pred)
#avg predicted and actual values

SST=0
for i in range(len(y)):
  SST+=(y[i]-y_avg)*(y[i]-y_avg)
  #getting sst values

SSE=0
for i in range(len(y)):
  SSE+=(y[i]-y_pred[i])*(y[i]-y_pred[i])
  #getting sse values

SSR=0
for i in range(len(y)):
  SSR+=(y_pred[i]-y_avg)*(y_pred[i]-y_avg)
  #getting ssr values

print("SST:",SST)
print("SSR:",SSR)
print("SSE:",SSE)

x_values= [1400,1600,1700,1875,1100,1550,2350,2450,1425,1700]
y_values=[245,312,279,308,199,219,405,324,319,255]
plt.scatter(x_values,y_values,color='blue',label='data points')
plt.xlabel('Square feet(x)')
plt.ylabel('House price(y)')
plt.title('House sq feet vs price plot')
plt.legend()
plt.grid(True)
plt.show()
#plotting graph pf x vs y

df=pd.read_csv("company_sales_data.csv")
df

import matplotlib.pyplot as plt

# Data from the provided table
month_number = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
total_profit = [211000, 183300, 224700, 222700, 209600, 201400, 295500, 361400, 234000, 266700, 412800, 300200]

plt.figure(figsize=(10, 6))
plt.plot(month_number, total_profit, marker='o')

# Adding labels and title
plt.xlabel('Month Number')
plt.ylabel('Total Profit')
plt.title('Total Profit per Month')

# Display the plot
plt.grid(True)
plt.show()

month_number = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
total_units = [21100, 18330, 22470, 22270, 20960, 20140, 29550, 36140, 23400, 26670, 41280, 30020]



plt.plot(month_number, total_units, linestyle='dotted', color='red', marker='o', markerfacecolor='red', markersize=8, linewidth=3)

plt.xlabel('Month Number')
plt.ylabel('Sold Units Number')
plt.title('Sold Units per Month')


plt.legend(['Sold Units'], loc='lower right')

# Display the plot
plt.grid(True)
plt.show()

month_number = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
facecream_units = [2500, 2630, 2140, 3400, 3600, 2760, 2980, 3700, 3540, 1990, 2340, 2900]
facewash_units = [1500, 1200, 1340, 1130, 1740, 1555, 1120, 1400, 1780, 1890, 2100, 1760]
toothpaste_units = [5200, 5100, 4550, 5870, 4560, 4890, 4780, 5860, 6100, 8300, 7300, 7400]
bathingsoap_units = [9200, 6100, 9550, 8870, 7760, 7490, 8980, 9960, 8100, 10300, 13300, 14400]
shampoo_units = [1200, 2100, 3550, 1870, 1560, 1890, 1780, 2860, 2100, 2300, 2400, 1800]
moisturizer_units = [1500, 1200, 1340, 1130, 1740, 1555, 1120, 1400, 1780, 1890, 2100, 1760]


plt.figure(figsize=(10, 4))
plt.plot(month_number, facecream_units, marker='o', label='Face Cream')
plt.plot(month_number, facewash_units, marker='o', label='Face Wash')
plt.plot(month_number, toothpaste_units, marker='o', label='Toothpaste')
plt.plot(month_number, bathingsoap_units, marker='o', label='Bathing Soap')
plt.plot(month_number, shampoo_units, marker='o', label='Shampoo')
plt.plot(month_number, moisturizer_units, marker='o', label='Moisturizer')


plt.xlabel('Month Number')
plt.ylabel('Sold Units Number')
plt.title('Product Sales per Month')


plt.legend(loc='upper left')


plt.grid(True)
plt.show()

month_number = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
toothpaste_units = [5200, 5100, 4550, 5870, 4560, 4890, 4780, 5860, 6100, 8300, 7300, 7400]


plt.figure(figsize=(10, 4))
plt.scatter(month_number, toothpaste_units, color='blue', marker='o')


plt.xlabel('Month Number')
plt.ylabel('Toothpaste Sold Units')
plt.title('Toothpaste Sales per Month')


plt.grid(True, linestyle='--')


plt.show()

month_number = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
bathingsoap_units = [9200, 6100, 9550, 8870, 7760, 7490, 8980, 9960, 8100, 10300, 13300, 14400]


plt.figure(figsize=(10, 6))
plt.bar(month_number, bathingsoap_units, color='green', alpha=0.7)


plt.xlabel('Month Number')
plt.ylabel('Bathing Soap Sold Units')
plt.title('Bathing Soap Sales per Month')


plt.grid(True)


plt.savefig('bathing_soap_sales.png')


plt.show()

month_number = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
total_profit = [211000, 183300, 224700, 222700, 209600, 201400, 295500, 361400, 234000, 266700, 412800, 300200]


plt.figure(figsize=(10, 6))
plt.hist(total_profit, bins=10, color='purple', edgecolor='black', alpha=0.8)

plt.xlabel('Total Profit')
plt.ylabel('Frequency')
plt.title('Distribution of Total Profit')


plt.grid(True)


plt.show()

facecream = [2500, 2630, 2140, 3400, 3600, 2760, 2980, 3700, 3540, 1990, 2340, 2900]
facewash = [1500, 1200, 1340, 1130, 1740, 1555, 1120, 1400, 1780, 1890, 2100, 1760]
toothpaste = [5200, 5100, 4550, 5870, 4560, 4890, 4780, 5860, 6100, 8300, 7300, 7400]
bathingsoap = [9200, 6100, 9550, 8870, 7760, 7490, 8980, 9960, 8100, 10300, 13300, 14400]
shampoo = [1200, 2100, 3550, 1870, 1560, 1890, 1780, 2860, 2100, 2300, 2400, 1800]
moisturizer = [1500, 1200, 1340, 1130, 1740, 1555, 1120, 1400, 1780, 1890, 2100, 1760]


total_sales = [
    sum(facecream), sum(facewash), sum(toothpaste),
    sum(bathingsoap), sum(shampoo), sum(moisturizer)
]

products = ['Face Cream', 'Face Wash', 'Toothpaste', 'Bathing Soap', 'Shampoo', 'Moisturizer']

plt.figure(figsize=(8, 8))
plt.pie(total_sales, labels=products, autopct='%1.1f%%', startangle=140, colors=plt.cm.Paired.colors)
plt.title('Total Sales Percentage for Last Year')


plt.show()

month_number = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
facewash_units = [1500, 1200, 1340, 1130, 1740, 1555, 1120, 1400, 1780, 1890, 2100, 1760]
bathingsoap_units = [9200, 6100, 9550, 8870, 7760, 7490, 8980, 9960, 8100, 10300, 13300, 14400]


plt.figure(figsize=(10, 10))


plt.subplot(2, 1, 1)
plt.plot(month_number, facewash_units, marker='o', color='blue')
plt.title('Facewash Sales')
plt.xlabel('Month Number')
plt.ylabel('Sold Units Number')
plt.grid(True)


plt.subplot(2, 1, 2)
plt.plot(month_number, bathingsoap_units, marker='o', color='green')
plt.title('Bathing Soap Sales')
plt.xlabel('Month Number')
plt.ylabel('Sold Units Number')
plt.grid(True)


plt.tight_layout()


plt.show()

month_number = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
facecream = [2500, 2630, 2140, 3400, 3600, 2760, 2980, 3700, 3540, 1990, 2340, 2900]
facewash = [1500, 1200, 1340, 1130, 1740, 1555, 1120, 1400, 1780, 1890, 2100, 1760]
toothpaste = [5200, 5100, 4550, 5870, 4560, 4890, 4780, 5860, 6100, 8300, 7300, 7400]
bathingsoap = [9200, 6100, 9550, 8870, 7760, 7490, 8980, 9960, 8100, 10300, 13300, 14400]
shampoo = [1200, 2100, 3550, 1870, 1560, 1890, 1780, 2860, 2100, 2300, 2400, 1800]
moisturizer = [1500, 1200, 1340, 1130, 1740, 1555, 1120, 1400, 1780, 1890, 2100, 1760]

plt.figure(figsize=(10, 6))
plt.stackplot(month_number, facecream, facewash, toothpaste, bathingsoap, shampoo, moisturizer,
              labels=['Face Cream', 'Face Wash', 'Toothpaste', 'Bathing Soap', 'Shampoo', 'Moisturizer'],
              alpha=0.7)


plt.xlabel('Month Number')
plt.ylabel('Sold Units Number')
plt.title('Product Sales per Month')


plt.legend(loc='upper left')

plt.show()