# -*- coding: utf-8 -*-
"""tutorial2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aBzFSz7FyMtnTYNUdvEvtTkGDSh_bCBy
"""

import pandas as pd
import matplotlib.pyplot as pyp
mydata = pd.read_csv("test_data.csv")
print(mydata)

mydata.mean()

mydata.head()

mydata.groupby("Survived").mean()

mydata.tail()

mydata.sort_values(by="Age")

mydata["Age"].value_counts()



d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack',
   'Lee','Chanchal','Gasper','Naviya','Andres']),
   'Age':pd.Series([25,26,25,23,30,25,23,34,40,30,25,46]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80,4.10,3.65])}
df = pd.DataFrame(d)
print (df.skew())

from pandas.core.groupby import groupby
d = {
   'Age':pd.Series([25,26,25,23,30,25,23,34,40,30,25,46]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,3.78,2.98,4.80,4.10,3.65])}
df1 = pd.DataFrame(d)
d2 = {
   'Age':pd.Series([25,26,25,23,30,25,23,36,47,99,99,999,]),
   'Rating':pd.Series([4.23,3.24,3.98,2.56,3.20,4.6,3.8,6.9,6.8,6.7,6.4,6.5])}
df2 = pd.DataFrame(d2)


print (df1.std())
print (df1.skew())

d = {'Name':pd.Series(['Tom','James','Ricky','Vin','Steve','Smith','Jack',
   'Lee','Chanchal','Gasper','Naviya','Andres']),
   'Age':pd.Series([25,26,25,23,30,25,23,34,40,30,25,46])}
#Create a DataFrame
df = pd.DataFrame(d)
print (df.mode())

#results
mydata[["Age", "Fare"]].median()

mydata[["Age", "Fare"]].median()

mydata[["Survived"]].groupby("Survived").mean()

pd.data